steps:
# Paso 1: Construir la imagen Docker (igual que antes)
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/gcp-devops-454205/devops-images/gcp-repo-01:$COMMIT_SHA'
  - '.'

# Paso 2: Subir la imagen a GCR (o Artifact Registry si prefieres)
# Asegúrate que la cuenta de servicio personalizada tenga permisos para esto
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-devops-454205/devops-images/gcp-repo-01:$COMMIT_SHA']

# Especifica las imágenes resultantes
images:
- 'us-central1-docker.pkg.dev/gcp-devops-454205/devops-images/gcp-repo-01:$COMMIT_SHA'

# === LA CLAVE: Configuración de Logging ===
options:
  logging: CLOUD_LOGGING_ONLY # Opciones: GCS_ONLY, CLOUD_LOGGING_ONLY, NONE, DEFAULT
